name: gstreamer

services:
  gstwebrtcapp-cuda:
    build:
      context: .
      dockerfile: Dockerfile-cuda
      args:
        CUDA_VER: "12.4"
        CUDA_VER_MINOR: "1"
        CUDNN_VER: "cudnn"
        UBUNTU_VER: "22.04"
      tags:
        - nsmirnov/gstwebrtcapp-cuda:latest
    image: nsmirnov/gstwebrtcapp-cuda:latest
    networks:
      - bridge
    ports:
      - "9090:9090/udp"
      - "9090:9090/tcp"
      - "8443:8443/udp"
      - "8443:8443/tcp"
      - "3478:3478/udp"
      - "3478:3478/tcp"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    runtime: nvidia
    privileged: true
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    command: [ "tail", "-f", "/dev/null" ]
    profiles:
      - cuda

  gstwebrtcapp-cpu:
    build:
      context: .
      dockerfile: Dockerfile-cpu
      args:
        UBUNTU_VER: "24.04"
      tags:
        - nsmirnov/gstwebrtcapp-cpu:latest
    image: nsmirnov/gstwebrtcapp-cpu:latest
    networks:
      - bridge
    ports:
      - "9090:9090/udp"
      - "9090:9090/tcp"
      - "8443:8443/udp"
      - "8443:8443/tcp"
      - "3478:3478/udp"
      - "3478:3478/tcp"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    privileged: true
    cap_add:
      - NET_ADMIN
    command: [ "tail", "-f", "/dev/null" ]
    profiles:
      - cpu

networks:
  bridge:
    driver: bridge
